### ISSUE TITLE
Bug in main.py

### ISSUE THREAD

**Issue by mirakilov-developer** [quvonchbek-dev/linalg-inv-matrix#1]
Quyidagicha kod yozilgan:
from src.App import MyApp

ammo App,py src paketida emas. Shunga from App import MyApp qilish kerak.

**Comment by quvonchbek-dev** [comment]
@mirakilov-developer yaxshi, qarab chiqaman

**Comment by quvonchbek-dev** [comment]
Issue fixed, you can check commit) @mirakilov-developer
